<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="PrequalificationResponse_V1" nillable="true" type="PrequalificationResponse_V1" />
  <xs:complexType name="PrequalificationResponse_V1">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="City" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Extension" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="HouseNumber" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Street" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ZipCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="IsraSpecs" type="ArrayOfString" />
      <xs:element minOccurs="0" maxOccurs="1" name="ServiceId" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="FtuType" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="NlsType" nillable="true" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="LineType" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Remarks" type="ArrayOfString" />
      <xs:element minOccurs="0" maxOccurs="1" name="ErrorClass" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ErrorMessage" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Products" type="ArrayOfAvailabilityProduct_V1" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfString">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfAvailabilityProduct_V1">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="AvailabilityProduct_V1" nillable="true" type="AvailabilityProduct_V1" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AvailabilityProduct_V1">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="ProductCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Availability" type="AvailabilityProductStatus_V1" />
      <xs:element minOccurs="0" maxOccurs="1" name="DistributionType" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="IsVectoring" nillable="true" type="xs:boolean" />
      <xs:element minOccurs="0" maxOccurs="1" name="TariffCluster" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="AvailabilityProductStatus_V1">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Unknown" />
      <xs:enumeration value="Red" />
      <xs:enumeration value="Yellow" />
      <xs:enumeration value="Green" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
